### ISSUE TITLE
mcrypt officially deprecated in PHP 7.1

### ISSUE THREAD

**Issue by HanFox** [marius-wieschollek/passwords-legacy#4]
> This extension has been deprecated as of PHP 7.1.0 and moved to PECL as of PHP 7.2.0.

See: https://github.com/marius-wieschollek/passwords/blob/stable/service/passwordservice.php

Seems a bit weird for an application that needs to be good with security to be using a library that hasn't been updated since 2007.

It doesn't look like an easy change to something like openssl. It's not a simple 1:1 update.

There is the issue data that is encrypted with mcrypt can't be easily decrypted by openssl so the easiest way around that would be to export the passwords manually, dump the old ones, then reimport them after the upgrade.

It was being looked at in the old app back in March, 2016: https://github.com/fcturner/passwords/issues/134

**Comment by marius-wieschollek** [comment]
Yes I do know about the mcrypt issue.

I will look at the possible ways to fix this.

**Comment by fcturner** [comment]
I could help with this one. I also want the migrate to openssl.

> so the easiest way around that would be to export the passwords manually, dump the old ones, then reimport them after the upgrade.

No, that's insecure and then all users must do this for their own passwords since admin cannot decrypt users passwords. It should be done via a PHP update whenever a users logs in in a new version (so passwords can be decrypted). I did a same kind of migration from v16 to v17. Just a huge database update for every user which runs when the user enters the app the first time in a new version. 

I think that this is almost entirely OC/NC independent, so maybe we should do this one together :wink:

**Comment by fcturner** [comment]
> Seems a bit weird for an application that needs to be good with security to be using a library that hasn't been updated since 2007.

True, but you can still encrypt with `mcypt` tremendously. You should notice that by looking at the code. Nevertheless, it's time for `openssl`.

**Comment by marius-wieschollek** [comment]
@fcturner working together on this sounds like a reasonable approach to me.

**Comment by pierre-alain-b** [comment]
But now fcturner has vanished from the web. We don't know why.

**Comment by e-alfred** [comment]
Well it happened the same time @brantje contacted him as it seems. He did not like Nextcloud and the security issues seem to be serious. Not good for a password manager.

**Comment by pierre-alain-b** [comment]
OK so I will recommand to my user to move to Passman I think...

**Comment by brantje** [comment]
When I get home I will provide some information about this

**Comment by brantje** [comment]
Back at home, here is my "story".

2 day's ago i stumbled upon fcturner/passwords, i saw the announcement where he said goodbye to Nextcloud for personal reasons, ok no problem there.
I rad on and saw he mentioned passman in this way `"This app (Passman) is not nearly as secure as Passwords"`. 
For me that claim was a reason to start digging into the README  & code.   
   
I saw that the app offers client and server side encryption.    
So i would start on the JS side, as JS is almost my native language.   
I fired up the chrome debugger, and saw the username / password being send in plain text.   
Oh that can't be good i thought, so i opened the app in the IDE and start looking for the client side encryption code.   
I din't find any.

So i moved over to the server side, and saw mcrypt being used, and made a note of that.
Other than that it was good.

I was interested in the auth, because it was possible to login with and without password.   
In the readme i saw ` (since encryption is performed with a key that is not known to the server)`.   
So i set it to use my password.    
I login, and i see my password, being send in plain text.

Last one, is the xss, was found by putting script tags in every input field 

So i created an issue about this at his repo:

**================================**
Hi there,
one of the Passman authors here.. I’ve noticed your statement so I have started digging in your app.

First things first:
You can clearly see that passwords app is sending the credentials in plain text to the server, so if someone is using HTTP, all their passwords will be exposed.
![image](https://user-images.githubusercontent.com/2758767/28995688-4ee18448-79f0-11e7-91b5-87d0093c6031.png)
According to this, your statement of "passwords is using client-side encryption" is incorrect, wrong, and misleading. If you were using client side encryption it would look like below, like on passman.


Passman on the other end sends the credentials encrypted to the server:
![image](https://user-images.githubusercontent.com/2758767/28995707-b4711e72-79f0-11e7-82a6-60098de08164.png)

Second one:
Your encryption class uses mcrypt_ functions which are deprecated in PHP 7.1.
As far I can see, you can copy our server side encryption class that is using the openssl lib.

Third one:
Auth password (and thus encryption password), are sent in plain text over the internet to server.
![image](https://user-images.githubusercontent.com/2758767/28995808-40e460ba-79f3-11e7-945f-d0b447dd8dd5.png)


Forth one:
XSS. Your app is vulnerable for [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting):
![image](https://user-images.githubusercontent.com/2758767/28996150-521bad14-79fa-11e7-8f3d-bfae22ba26f0.png)
Results in:
![image](https://user-images.githubusercontent.com/2758767/28996152-614f31e8-79fa-11e7-8a2e-4d0d296deff5.png)

So to sum this all up, to me it seems passman is more secure than passwords app, and therefore the statement "Passman app is not nearly as secure as Passwords ." seems invalid to me
I ask you therefore to add client side encryption or remove said statement, it’s misleading users to believe you encrypt passwords before sending them to the server (at the client side, not at the server side).

In the future, we would appreciate if you raised an issue, or contact us directly about our encryption before using words like "abysmal" without justification.

** ================ END ================ **

Turner replied, he was not amused about this, i only post what i remember him saying.
`Nice, thanks for bashing. Really gets the fire on the oil war between OC and NC. Pathetic.`

Then about this part:
"You can clearly see that passwords app is sending the credentials in plain text to the server, so if someone is using HTTP, all their passwords will be exposed."
`Passwords won't send them unless you turn off the option, you moron`

Ok, maybe i was wrong about that, but what about the so said client side encryption?

"Your encryption class uses mcrypt_ functions which are deprecated in PHP 7.1"
Here he referred to an open issue (like this one)

![image](https://user-images.githubusercontent.com/2758767/29132623-1e2546ca-7d31-11e7-85dd-4bdf77673774.png)

And he ignored the report of XSS.

Next day, the issue's were disabled and the readme was updated:
```
Just an awesome password manager. Take it or leave it. I'm tired of all discussions, so no more issue tracking. Use this app if you like. I will maintain it on my own for ownCloud only.
```

Not short after that he removed is entire account.

**Comment by pierre-alain-b** [comment]
Thank you for reporting this and being transparent (it is the least to say that the original author of Passwords was apparently not, based on this account). The analysis of the code will certainly prove helpful to others when evaluating the merits/security of different password managers.

@marius-wieschollek, if you agree with this analysis, maybe it would be good to put a foreword on the readme page. Your work will be valuable to all those who would like to stick to Passwords but I think users shall be informed of the potential risks unless they are fixed in future releases.

Thank you all for your actions around this.

**Comment by brantje** [comment]
May i ask, why we want to have two password managers for Nextcloud?
What does Passman lacks that Passwords has? 
I (and i'm sure others), rather see 1 app then 2. (Fart apps anyone?)

Passman is build using Angular js, and works on Nextcloud and ownCloud.
The webextension is build using jQuery and the web extension api.
And there is also an Android app.

I'm not asking to give up passwords right away, but we can make the transition from Passwords to Passman painless if you like. 

Just let me know where you would like to work on and i'll invite you to the repo.

**Comment by pierre-alain-b** [comment]
I was not implying that Passman is lacking any feature :-) 
As far as I am concerned, I have started to advise around me to transition to Passman.
I am sure a visual doc on how to easily transfer password from Passwords to Passman would help. I have no idea how many people may be using Passwords out there.

**Comment by HanFox** [comment]
This really isn't the correct place to be discussing Passman vs Passwords as it's an issue about mcrypt.

Regardless, I'm sure @marius-wieschollek can tidy it up when he can, so I shall state why I don't use Passman:

After fctuner originally announced dropping support for NC I tried Passman. The UI is kinda clunky. I found I had to dig around a bit too much for what should be simple. It's not about features (as both technically do the same... store passwords) it's about the UI and I really don't like Passman.

If Passman added an alternative UI that was much more similar to Passwords I'd quite happily use it, but as it is I hope that @marius-wieschollek (and others) can find the time to keep this fork going.

**Comment by marius-wieschollek** [comment]
Well, @HanFox is right. The right place to discuss the future of this app should be a separate issue. But here we are, so i will answer a few of the questions and give you a bit of transparency.
There is an issue for the Client-Side-Encryption ( #8 ) and the XSS stuff ( #9 ). Maybe I should also create an issue for the JSON API, because it is a big pile of garbage.
Right now I am unsure whether i should rewrite this app piece by piece, start from scratch or just migrate to Passman.

**Why am I using Passwords in the first place?**
When i first set up my ownCloud 6.x, I just went trough their appstore and installed any app that looked good. I kept those that actually did what they should. At that point i just scrolled trough the app description and believed what it said. Sometime later I discovered that I had to use the git version in order to get updates on time, because the author did not like the original appstore. When i read the readme of the repo and discovered that it was using mcrypt i was a little concerned but then just ignored it. When i moved to Nextcloud and read the authors rants about it, i could kind of understand him, because neither the code of Nextcloud/ownCloud nor its documentation is _that_ good. Earlier this year i first started to look at the source code, because the never ending beta 20 had a bug which prevented the whole app from working and it seemed like no one wanted to fix it or could fix it. At that time i first looked t the code and basically discovered the things we all know for sure now: The claims about the encryption are not true, the JSON API is a mess, mostly because the author refuses to use system provided methods. I fixed the bug and started looking for alternatives. As you can see i'm still here.

**Why am I not using Passman?**
I have considered Passman a few times now. But i would agree with @HanFox again. The interface looks bad, the German translation is confusing and it is simply too complex for a simple task. I have not looked at the code, but as far as i can see the security stands and falls with how safe the application handles the private key. I think it is an alternative, and the Firefox Add-on is actually a real plus.

**What do I want to do with Passwords?**
I really would like to make it an easy to use, minimalistic yet safe password store. My idea would be an interface which looks pretty much like files app, just with passwords instead of files. (I want to introduce folders, but the default view would be an "All Passwords" folder). Of course I want to fix the security issues and replace the api.

**Am i capable of this?**
I think yes. I work with PHP professionally since years, mostly with enterprise cms systems. I have implemented openssl in php before. I am not a backend only developer, but i'm not a genius in frontend stuff. Don't expect the newest and most fancy whatever stuff. That's it abut the pros, However this is the first time i am writing a Nextcloud app. It is also the first time i am maintaining an open source project. Usually i use my private GitLab server, so don't be surprised when you find a gitlab-ci.yml here soon. If i'm busy, the app will have to wait.

**What is coming next?**
I am trying to get in touch with the extension developers, to see if they want to continue their work. If they don't, i will check if i can provide a Passman compatible api. If i do not continue this project i will at least fix the XSS stuff and provide Nextcloud fixes for one more version so you can migrate. I will update the readme as soon as i am back home in a few weeks.

**Is there a catch?**
I will make a minimal version of the app. You should have a recent system, minimum PHP 7.1. If you have Ubuntu, [go here](https://launchpad.net/~ondrej/+archive/ubuntu/php/). You need Nextcloud 12. I will not provide 25 languages. It will be German and English, but of course you can help expanding that.

**How do i migrate to Passman**
Allow users to download a unencrypted backup in the admin settings. Your users can download the backup in the settings and import it in the Passman settings after they have created their safe. You could create the export file for all your users yourself, after all there is no client side encryption there to stop you. I'm not helping with that.

**Comment by pierre-alain-b** [comment]
Thank you @marius-wieschollek, this seems a very reasonable roadmap!

**Comment by e-alfred** [comment]
Actually, there is Keeweb too, for opening up Keepass databases. So basically there are already two password managers.

Migrating to Passman from Passwords is quite easy, exporting the passwords as *.csv and importing them into Passman works quite well. The only requirement is doing it before an upgrade to the latest Nextcloud release.

That said, I think the UI with "Vaults" is probably not the thing everybody likes. A flat view is quite nice to have and it also allows sharing of passwords without other people having to create a vault too. This is a big advantage of it.

**Comment by pafcioooo** [comment]
HI Everybody,

Since I am also still Passwords app user and tried Passman as well I will also add my 2 cents to this nice Passman vs Passwords conversation.

The clue reason for Passwords vs Passman is what @e-alfred said:

> I think the UI with "Vaults" is probably not the thing everybody likes. A flat view is quite nice to have and it also allows sharing of passwords without other people having to create a vault too. This is a big advantage of it.

I think for the sake of all of us using Nextcloud there should be one really good passwords app, so maybe joining forces is not so bad idea:-)

**Comment by HanFox** [comment]
In regards to what this is actually about (mcrypt being deprecated) PHP 7.2 is now officially released.

Any news about moving to openssl or similar?

**Comment by marius-wieschollek** [comment]
@HanFox Yes, I'm [rewriting the core](https://github.com/marius-wieschollek/passwords). Planned to be finished at the end of january.

**Comment by marius-wieschollek** [comment]
I would like to inform you, that i have finished most of the [new app](https://github.com/marius-wieschollek/passwords). It would be great if you could take a look at the [legacy migration guide](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration) and test if the migration makes any problems with your database. This way you can help to make sure that no problems occur when the final app is distributed over the nextcloud app store.

**Comment by marius-wieschollek** [comment]
The first [nightly build](https://apps.nextcloud.com/apps/passwords) of the rewritten app is now in the Nextcloud app store. A stable version will follow next week. So the last thing to say here is that you should make sure that you are on PHP 7.1 for the upgrade. Lower versions are not supported by the app and newer versions don't support mcrypt.
