### ISSUE TITLE
Client side encryption

### ISSUE THREAD

**Issue by brantje** [marius-wieschollek/passwords-legacy#8]
Hi there,
I did some research on the app and discovered that the app is sending the credentials in plain text:
![image](https://user-images.githubusercontent.com/2758767/28995688-4ee18448-79f0-11e7-91b5-87d0093c6031.png)
Don't mind the domain, it's a nextcloud install, too lazy to generate a new cert. 

In the readme it say's there is client side encryption, so why does the app send the credentials in plain text?
Also i assume this is the same for the fcturner's app

**Comment by marius-wieschollek** [comment]
This is correct.
My app is a fork of https://github.com/fcturner/passwords and api compatible with it. So far I have only added support for Nextcloud 12 to the original app.

The api is described on https://github.com/fcturner/passwords/wiki/ownCloud-Passwords-%7C-RESTful-API . The api is only safe if you use it with https. The api also does not send any data without proper authorization.

As far as i have checked the code, there is **no client side encryption**. There are different keys which are used to encrypt the passwords, but all keys are known to the server. The readme claims that there are user and password specific keys, however the user specific key is the username and the password specific key is the website.
Since the migration from the deprecated mcrypt php extension to openssl requires the update of all keys, i will use this chance to add support for client side encryption. This will take some time. Also I may make the original api optional, but as long as it is enabled, the client side key must be known to the server.

PS: If that is not demo data in the screenshot, please change your password :D.

**Comment by brantje** [comment]
Oh that is demo data, forgot to change it to `super secret password` what my password is for everywhere ;). 
Could you please update the read me then, if it doesn't contain client side encryption, it's misleading information. I tried to tell fcturner that, + the XSS issue, but got called out for moron and the issue was closed and clock.
```
This app features both server-side encryption (since encryption takes place on the server, before the data is placed in the database table) and >>> client-side encryption (since encryption is performed with a key that is not known to the server) <<<. All passwords (generated or your own) are stored into your own ownCloud/NextCloud database, using these high-end cryptological functions:
```

**Comment by marius-wieschollek** [comment]
I am closing this issue since this app is EOL and will not receive a client side encryption. The new app will receive client side encryption by mid 2018.
